### ISSUE TITLE
Pluggable test plans (via manifests)

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#32]
~Currently, test plans are part of the source tree of the test ground. It would be nice to define a clean, lightweight, abstract API between the testground and testplans, such that test plans could be built and loaded as plugins.~

~https://godoc.org/plugin~

EDIT: after a conversation with @Stebalien, Go plugins are difficult and unergonomic to use. Instead, we're detaching test plans by introducing a "test plan manifest" -- which is a descriptor of the test plan, the supported build strategies, run strategies, and its test cases.

Example:

```toml
name = "dht"
# hashicorp/go-getter URLs, so in the future we can support fetching test plans
# from GitHub.
source_path = "file:${TESTGROUND_REPO}/plans/dht"

[[ build_strategies ]]
type = "executable:go"
go_version = "1.13"
module_path = "github.com/ipfs/testground/plans/dht"
exec_pkg = "exec"

[[ build_strategies ]]
type = "docker:go"
go_version = "1.13"
module_path = "github.com/ipfs/testground/plans/dht"
exec_pkg = "exec"

[[ run_strategies ]]
type = "local:binary"

[[ run_strategies ]]
type = "local:docker"

[[ run_strategies ]]
type = "distributed:nomad"

[[testcases]]   # seq 0
name = "lookup-peers"
instances = { min = 2, max = 100, default = 50 }

  [testcases.params.bucket_size]
  type = "int"
  desc = "bucket size"
  unit = "peers"

[[testcases]]   # seq 1
name = "lookup-providers"
instances = { min = 2, max = 100, default = 50 }

  [testcases.params.bucket_size]
  type = "int"
  desc = "bucket size"
  unit = "peers"

[[testcases]]   # seq 2
name = "store-get-value"
instances = { min = 2, max = 100, default = 50 }
roles = ["storer", "fetcher"]

  [testcases.params.bucket_size]
  type = "int"
  desc = "bucket size"
  unit = "peers"
```
