### ISSUE TITLE
sidecar gets OOMKilled in k8s

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#385]
Sidecar gets OOMKilled in k8s, when running 500 testplan instances:

```
➜  ~ testground -vv run dht/find-peers \
    --builder=docker:go \
    --runner=cluster:k8s \
    --build-cfg bypass_cache=true \
    --build-cfg push_registry=true \
    --build-cfg registry_type=aws \
    --run-cfg log_level=debug \
    --instances=500
```

The config for `sidecar` used is:

```
    spec:
      terminationGracePeriodSeconds: 10
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: testground-sidecar
        image: nonsens3/testground
        command: ["testground"]
        args: ["--vv", "sidecar", "--runner", "k8s"]
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_ADMIN", "SYS_TIME"]
          privileged: true
        env:
        - name: REDIS_HOST
          value: "redis-master"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
          - name: dockersock
            mountPath: "/var/run/docker.sock"
          - name: cnibin
            mountPath: "/host/opt/cni/bin"
```
