### ISSUE TITLE
compositions is missing important --build-cfg flags

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#496]
At the moment it seems like it is not possible to set the following flags, when running a composition test
```
    --build-cfg push_registry=true \
    --build-cfg registry_type=aws \
```

**Comment by raulk** [comment]
This bug report needs a composition TOML that reproduces the issue.

**Comment by aschmahmann** [comment]
Failing composition TOML

```toml
[metadata]
  name = "find-provs"
  author = "adin"

[global]
  plan = "dht"
  case = "find-providers"
  total_instances = 50
  builder = "docker:go"
  runner = "cluster:k8s"
  [global.build_config]
    push_registry = "true"
    registry_type = "aws"

[[groups]]
  id = "balsa"
  [groups.instances]
    count = 0
    percentage = 0.0
  [groups.build]
  [groups.run]
    artifact = "aa9b081106c7"
    [groups.run.test_params]
      bucket_size = "4"
      client_mode = "false"
      f_undialable = "0.9"
      n_providing = "1"
      record_count = "5"
      timeout_secs = "2000"

[[groups]]
  id = "cypress"
  [groups.instances]
    count = 0
    percentage = 1.0
  [groups.build]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "v0.4.2-0.20200204202258-35d3e4a5d43e"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-autonat"
      version = "v0.1.2-0.20200204200147-902af8cb7b6a"
  [groups.run]
    artifact = "3e85d1127ec8"
    [groups.run.test_params]
      bucket_size = "4"
      client_mode = "false"
      f_undialable = "0.9"
      n_providing = "1"
      record_count = "5"
      timeout_secs = "300"

```
