### ISSUE TITLE
Composition Validation

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/testground#532]
If I have a composition with both count and percentage set like:

```toml
[[groups]]
  id = "g1"
  [groups.instances]
    count = 0
    percentage = 1.0

[[groups]]
  id = "g2"
  [groups.instances]
    count = 0
    percentage = 0.0
```

The composite will run and not give any errors. The intention seems to be that it errors from https://github.com/ipfs/testground/blob/39da173752b60af271cf5422e827570ad74b0056/pkg/api/composition.go#L185
