### ISSUE TITLE
Composition zero percentage not respected

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/testground#539]
If you have a composition file like the one below, you may end up with some instances of g2 despite the percentage being set to zero.

```toml
[[groups]]
  id = "g1"
  [groups.instances]
    count = 0
    percentage = 1.0

[[groups]]
  id = "g2"
  [groups.instances]
    count = 0
    percentage = 0.0
```

Note: `testground run composition -f composition.toml -i -w` fills `count = 0` which may or may not be relevant here.
