### ISSUE TITLE
prometheus appears to not be configurable

### ISSUE THREAD

**Issue by nonsense** [ipfs/testground#631]
Currently we install `prometheus` as a `kops addon` at `cluster.yaml`:

```
spec:
  addons:
  - manifest: metrics-server
  - manifest: prometheus-operator
  - manifest: kubernetes-dashboard
```

I can't find any way to change the initial configuration, as it appears to be picking up configs from:
https://github.com/kubernetes/kops/tree/master/addons/prometheus-operator

We need a way to customize the scrape endpoints, so that we can install custom exporters, such as:

https://github.com/oliver006/redis_exporter or
https://github.com/helm/charts/tree/master/stable/prometheus-redis-exporter

---

It might be worth installing `prometheus` from `https://github.com/helm/charts/tree/master/stable/prometheus`, which is configurable and we can override any values in `values.yaml` we want.
