### ISSUE TITLE
weave resource limits may be too low for tests with many concurrent connections

### ISSUE THREAD

**Issue by yusefnapora** [ipfs/testground#856]
#### Version information:

This was on commit e60fde6a94f100cfe2a33d9174f26413c80ebe31 from the PL testground-fork repo.

#### Description:

When running with 3000 peers, we were seeing several weave instances failing just after the test started, and our test instances were never reaching the "all networks initialized" state.

Recreating the cluster with the limits below seems to have done the trick, and now the tests that were previously failing are completing successfully.  

relevant snippet from `infra/k8s/kops-weave/weave.yml`:

```yaml
              image: 'nonsens3/weave-kube'
              readinessProbe:
                httpGet:
                  host: 127.0.0.1
                  path: /status
                  port: 6784
              resources:
                requests:
                  memory: 1000Mi
                  cpu: 100m
```

I'm not 100% sure this was the root cause of our issues; there may have been other problems with the cluster that were fixed just be recreating it. But it may be worth bumping these up.

cc @nonsense
