### ISSUE TITLE
Test plans shouldn't specify regions

### ISSUE THREAD

**Issue by Stebalien** [ipfs/testground#90]
Ideally, we'd abstract over this. Test authors shouldn't have to care about amazon regions.

Instead, this should probably be something along the lines of:

```yaml
localLatency: "10ms"
globalLatency: "100ms"
regions:
  first: 5
  second: 10
latencies:
  - from: 5
    to: 10
    latency: "500ms"
```

(or something like that)
